version: '1'
services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@pedrofalfanfs_tp?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=fs_sum2_b
      - spring.datasource.password=Duoc_2024_sum2
    restart: always